# CodeRabbit AI Code Review Configuration
# Learn more: https://docs.coderabbit.ai/guides/review-instructions

language: en-US
early_access: false
enable_free_tier: true

# Review configuration
reviews:
  # Request review for specific users
  request_changes_workflow: false
  
  # High level summary at the top of the review
  high_level_summary: true
  
  # Poem style for summary (fun, concise, informative)
  poem: true
  
  # Review level (comprehensive > simple)
  review_status: true
  
  # Collapse walkthrough details by default
  collapse_walkthrough: false
  
  # Auto-approve PRs that meet quality standards
  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false
  
  # Path filters (exclusion patterns)
  path_filters:
    # Build artifacts and dependencies
    - "!**/*.min.js"
    - "!**/*.min.css"
    - "!**/dist/**"
    - "!**/build/**"
    - "!**/node_modules/**"
    - "!**/pnpm-lock.yaml"
    - "!**/package-lock.json"
    - "!**/yarn.lock"
    
    # Generated files
    - "!**/gen/**"
    - "!**/*.gen.ts"
    - "!**/*.gen.js"
    
    # Documentation assets
    - "!**/*.png"
    - "!**/*.jpg"
    - "!**/*.jpeg"
    - "!**/*.gif"
    - "!**/*.svg"
    - "!**/*.ico"
    
    # Configuration
    - "!**/.env*"
    - "!**/tsconfig*.json"
    
    # Blockchain artifacts
    - "!**/broadcast/**"
    - "!**/out/**"
    - "!**/cache/**"
  
  # Path-specific instructions
  path_instructions:
    - path: "packages/**"
      instructions: |
        - Ensure subpath exports are defined in package.json (e.g., "@repo/utils/async", "@repo/error/node")
        - Verify dual-mode exports (ESM/CJS) for compatibility
        - Check that no server-only code leaks into client bundles (no fs, path, env loaders in shared/browser code)
        - Validate TypeScript types are correctly exported
        - Ensure platform-specific exports are used (e.g., @repo/error/node vs @repo/error/nextjs)
        - Verify no root exports for packages with subpath exports
    
    - path: "apps/wallet/**"
      instructions: |
        - Follow Next.js 15 App Router conventions
        - Use React Server Components by default - only add 'use client' when absolutely necessary (interactivity, hooks, browser APIs)
        - Validate error boundaries are in place using @repo/error/nextjs
        - Check mobile-first responsive design patterns
        - Ensure no console.* usage - use @repo/utils/logger instead
        - Verify proper error handling with captureError from @repo/error/nextjs
        - Check that pages/layouts use default exports (exception to named exports rule)
    
    - path: "apps/mathler/**"
      instructions: |
        - Follow Next.js 15 App Router conventions
        - Use React Server Components by default - only add 'use client' when absolutely necessary (interactivity, hooks, browser APIs)
        - Validate error boundaries are in place using @repo/error/nextjs
        - Check mobile-first responsive design patterns
        - Ensure no console.* usage - use @repo/utils/logger instead
        - Verify proper error handling with captureError from @repo/error/nextjs
        - Check that pages/layouts use default exports (exception to named exports rule)
    
    - path: "apps/docu/**"
      instructions: |
        - Follow Next.js 15 App Router conventions
        - Use React Server Components by default
        - Ensure MDX content follows documentation standards
        - Verify cross-references use standard markdown links (e.g., [text](/docs/path)) not @ syntax
        - Check that documentation is up to date with code changes
    
    - path: "apps/fastify/**"
      instructions: |
        - Follow Fastify functional patterns (no classes or decorators)
        - Use TypeBox schemas for route validation (not Zod on backend)
        - Ensure proper error handling with @repo/error/node and captureError
        - Validate logger usage from @repo/utils/logger (never console.*)
        - Check OpenAPI schema generation is correct
        - Verify error handler plugin uses request.log for proper request context
        - Ensure ESM patterns (no __dirname/__filename, use import.meta.url)
    
    - path: "contracts/**"
      instructions: |
        - Follow Solidity best practices for EVM contracts
        - Follow Anchor patterns for Solana contracts
        - Verify security best practices (no reentrancy, proper access control)
        - Check that tests use real networks/APIs where appropriate
    
    - path: "**/*.{ts,tsx}"
      instructions: |
        - Follow RORO pattern (receive object, return object) for multiple parameters
        - Prefer functional code - avoid classes and decorators (except framework requirements)
        - Avoid unnecessary curly braces for single-line conditionals and arrow functions
        - Use explicit return types for exported functions and API handlers
        - Prefer interfaces over types for object shapes
        - Use import type for type-only imports
        - Verify no console.* usage - use @repo/utils/logger instead
        - Check that error handling uses @repo/error with platform-specific imports
        - Note: Backend API routes use TypeBox for validation, frontend/Next.js apps use Zod for API boundary validation
    
    - path: "**/*.{test.ts,test.tsx,spec.ts,spec.tsx,e2e-spec.ts}"
      instructions: |
        - CRITICAL: Integration tests must use real APIs with real API keys - NO MOCKS for core functionality
        - UI-only tests may mock API calls for performance, but integration tests must use real APIs
        - Verify test describes what is being tested clearly
        - Check edge cases are covered
        - Ensure mocks are properly cleaned up (if used for UI-only tests)
        - Validate assertions are meaningful
        - For API tests: verify all CRUD operations, error handling, response validation against OpenAPI schemas
    
    - path: ".cursor/**"
      instructions: |
        - Ensure rules follow MDC format with frontmatter
        - Validate skills have clear SKILL.md structure
        - Check documentation is up to date
        - Verify cross-references use @ syntax correctly
    
    - path: "**/*.{ts,tsx,js,jsx}"
      instructions: |
        - SECURITY: Never expose secrets in code (API keys, tokens, passwords)
        - SECURITY: Always validate server-side - never trust client-side validation alone
        - SECURITY: Use TypeBox schemas for backend API route validation, Zod schemas for frontend/Next.js API boundary validation
        - SECURITY: Never log secrets - use logger redaction features
        - LINTING: Code must pass both Biome (formatting/style) and ESLint (correctness) before merge
        - LINTING: Run pnpm lint:fix after making changes
        - LINTING: File size limit is 300 lines (exempt: test files and UI components)

# Chat configuration
chat:
  # Enable AI chat responses on PR comments
  auto_reply: true
